No exceptions occurred
I am inside finally block
Test completed
