There was an exception
Test completed
